### ISSUE TITLE
pio_rotary_encoder.pio.h not found

### ISSUE THREAD

**Issue by tianrking** [GitJer/Rotary_encoder#1]
pio_rotary_encoder.pio.h

**Comment by GitJer** [comment]
Besides the fact that this is an old repository, the new one is [here](https://github.com/GitJer/Some_RPI-Pico_stuff/tree/main/Rotary_encoder), the SDK compiles the .pio file into a .pio.h file. The .pio.h file can usually be found in a build folder.
